title: rIoT
description: "rIoT blog"
author:
  name: "rIoT"
  email: "itsusgame@gmail.com"
  url: "https://itsusgame.github.io/rIoT/"

baseurl: /rIoT

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "rIoT"
year : "2024"
